export const permissions = [
  {
    listCurso: false,
    viewCurso: false,
    createCurso: false,
    editCurso: false,
    deleteCurso: false,
    listDisciplina: false,
    viewDisciplina: false,
    createDisciplina: false,
    editDisciplina: false,
    deleteDisciplina: false,
    listAluno: false,
    viewAluno: false,
    createAluno: false,
    editAluno: false,
    deleteAluno: false,
    listMatricula: false,
    viewMatricula: false,
    editMatricula: false,
    createMatricula: false,
    deleteMatricula: false,
  },
  // COORDENADOR - 1
  {
    listCurso: true,
    viewCurso: true,
    createCurso: true,
    editCurso: true,
    deleteCurso: true,
    listDisciplina: true,
    viewDisciplina: true,
    createDisciplina: true,
    editDisciplina: true,
    deleteDisciplina: true,
    listAluno: true,
    viewAluno: true,
    createAluno: true,
    editAluno: true,
    deleteAluno: true,
    listMatricula: true,
    viewMatricula: true,
    editMatricula: true,
    createMatricula: true,
    deleteMatricula: true,
  },
  // PROFESSOR - 2
  {
    listCurso: true,
    viewCurso: true,
    createCurso: true,
    editCurso: false,
    deleteCurso: false,
    listDisciplina: true,
    viewDisciplina: true,
    createDisciplina: true,
    editDisciplina: false,
    deleteDisciplina: false,
    listAluno: true,
    viewAluno: true,
    createAluno: true,
    editAluno: false,
    deleteAluno: false,
    listMatricula: true,
    viewMatricula: true,
    editMatricula: false,
    createMatricula: false,
    deleteMatricula: false,
  },
]
